### PR TITLE
update dependencies

### LINKED ISSUE #96: Update to Grunt 1.0.0
Grunt released [version 1.0.0](https://github.com/gruntjs/grunt/releases).
Could you please update `grunt-processhtml`?
Currently this throws an error on my build process where I use Grunt 1.0.0

### PR DESCRIPTION
**Pull request by marcobiedermann**
Update all dependencies fix #96

### CODE REVIEW

**Comment by dciccale** [comment]
@marcobiedermann why is this failing?

**Comment by marcobiedermann** [comment]
@dciccale I think it failed because of an outdated Node version.
I merged the changes on `master` in it and all tests work fine with the newly set up versions `5.1`, `4.4` and `0.12`

**Comment by dciccale** [comment]
maybe there are breaking changes on grunt 1+.. it could make sense releasing a major version, need to do more research

**Comment by marcobiedermann** [comment]
@dciccale 
> Be advised Grunt 1.0.0 will no longer support Node.js v0.8.

Hmm … The previous tests were run against Node.js v0.10, so this might not be the issue

**Comment by dciccale** [comment]
i mean more of inside grunt APIs.. methods, etc, but I guess that if tests pass we are good to go..

**Pull request merged**
